import uuid
from datetime import datetime

from sqlalchemy import DateTime, func, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

# sort_order keeps the physical column order readable: id first, timestamps
# last, with each model's own columns in between. Without it, mixin columns
# sort ahead of everything by declaration counter.
_PK_ORDER = -100
_TS_ORDER = 100


class UUIDPrimaryKeyMixin:
    """UUID primary key generated by Postgres, not by Python.

    gen_random_uuid() is built into Postgres 13+ (no pgcrypto extension), so
    rows inserted by hand in psql or pgAdmin get a valid id too -- which a
    Python-side default cannot do.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
        sort_order=_PK_ORDER,
    )


class CreatedAtMixin:
    """For append-only tables, which have nothing to update."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        sort_order=_TS_ORDER,
    )


class TimestampMixin(CreatedAtMixin):
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
        sort_order=_TS_ORDER + 1,
    )
