"""initial dealpilot schema

Revision ID: 0002_schema
Revises: 0001_pgvector
Create Date: 2026-09-24 14:34:51.188578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Autogenerate renders the embedding column as
# `pgvector.sqlalchemy.vector.VECTOR(dim=...)` but never emits this import,
# so a generated migration touching document_chunks fails with NameError
# until it is added by hand. Re-check this after every autogenerate.
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '0002_schema'
down_revision: Union[str, None] = '0001_pgvector'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Native enum types created implicitly by the CREATE TABLE statements below.
# Alembic's autogenerated downgrade drops the tables but leaves these behind,
# so a downgrade/upgrade round trip fails with 'type ... already exists'.
# Listed literally rather than imported from app.models.enums: a migration
# must keep describing the schema as it was when written, even after the
# application's enums move on.
ENUM_TYPES: Sequence[str] = (
    "analysis_status",
    "buying_role",
    "chat_role",
    "chat_scope",
    "claim_type",
    "commitment_status",
    "deal_stage",
    "document_source_type",
    "fact_status",
    "influence_level",
    "ingest_status",
    "meeting_status",
    "message_status",
    "origin",
    "owner_side",
    "priority",
    "recommendation_status",
    "risk_level",
    "risk_status",
    "sentiment",
    "severity",
    "source_kind",
    "task_status",
    "validation_method",
    "verdict",
    "verification_status",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('employee_band', sa.String(length=50), nullable=True),
    sa.Column('hq_region', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts'))
    )
    op.create_table('claim_validations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('claim_type', sa.Enum('fact', 'commitment', 'risk', 'recommendation', 'chat_message', name='claim_type'), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('verdict', sa.Enum('supported', 'partial', 'contradicted', 'unsupported', name='verdict'), nullable=False),
    sa.Column('method', sa.Enum('deterministic', 'llm', 'human', name='validation_method'), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('validator_version', sa.String(length=50), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claim_validations'))
    )
    op.create_index('ix_claim_validations_claim_type_claim_id_checked_at', 'claim_validations', ['claim_type', 'claim_id', 'checked_at'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_contacts_account_id_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts')),
    sa.UniqueConstraint('account_id', 'email', name='account_email')
    )
    op.create_index(op.f('ix_contacts_account_id'), 'contacts', ['account_id'], unique=False)
    op.create_table('deals',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False),
    sa.Column('stage', sa.Enum('qualification', 'discovery', 'evaluation', 'security_and_legal', 'negotiation', 'closed_won', 'closed_lost', name='deal_stage'), nullable=False),
    sa.Column('win_probability', sa.SmallInteger(), nullable=True),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', name='risk_level'), nullable=True),
    sa.Column('expected_close_date', sa.Date(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('win_probability IS NULL OR (win_probability >= 0 AND win_probability <= 100)', name=op.f('ck_deals_win_probability_range')),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_deals_account_id_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deals'))
    )
    op.create_index(op.f('ix_deals_account_id'), 'deals', ['account_id'], unique=False)
    op.create_index('ix_deals_stage_expected_close_date', 'deals', ['stage', 'expected_close_date'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('scope', sa.Enum('global', 'deal', name='chat_scope'), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(scope = 'deal') = (deal_id IS NOT NULL)", name=op.f('ck_chat_sessions_deal_scope_needs_deal')),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('fk_chat_sessions_deal_id_deals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_sessions'))
    )
    op.create_index(op.f('ix_chat_sessions_deal_id'), 'chat_sessions', ['deal_id'], unique=False)
    op.create_table('deal_contacts',
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('buying_role', sa.Enum('champion', 'economic_buyer', 'technical', 'blocker', 'influencer', 'unknown', name='buying_role'), server_default='unknown', nullable=False),
    sa.Column('influence', sa.Enum('low', 'medium', 'high', 'unknown', name='influence_level'), server_default='unknown', nullable=False),
    sa.Column('sentiment', sa.Enum('positive', 'neutral', 'negative', 'unknown', name='sentiment'), server_default='unknown', nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_deal_contacts_contact_id_contacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('fk_deal_contacts_deal_id_deals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('deal_id', 'contact_id', name=op.f('pk_deal_contacts'))
    )
    op.create_table('deal_stage_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('from_stage', sa.Enum('qualification', 'discovery', 'evaluation', 'security_and_legal', 'negotiation', 'closed_won', 'closed_lost', name='deal_stage'), nullable=True),
    sa.Column('to_stage', sa.Enum('qualification', 'discovery', 'evaluation', 'security_and_legal', 'negotiation', 'closed_won', 'closed_lost', name='deal_stage'), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('fk_deal_stage_history_deal_id_deals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deal_stage_history'))
    )
    op.create_index(op.f('ix_deal_stage_history_deal_id'), 'deal_stage_history', ['deal_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.Enum('meeting_transcript', 'email', 'proposal', 'contract', 'note', name='document_source_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('storage_uri', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ingest_status', sa.Enum('pending', 'parsing', 'chunking', 'embedding', 'ready', 'failed', name='ingest_status'), server_default='pending', nullable=False),
    sa.Column('ingest_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_documents_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('fk_documents_deal_id_deals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('content_hash', name='content_hash')
    )
    op.create_index('ix_documents_deal_id_occurred_at', 'documents', ['deal_id', 'occurred_at'], unique=False)
    op.create_table('risks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('risk_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='severity'), nullable=False),
    sa.Column('status', sa.Enum('open', 'mitigating', 'resolved', 'dismissed', name='risk_status'), server_default='open', nullable=False),
    sa.Column('origin', sa.Enum('user', 'ai', name='origin'), server_default='ai', nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('first_detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("risk_type IN ('no_economic_buyer', 'single_threaded', 'stalled_stage', 'close_date_at_risk', 'unresolved_objection', 'security_review_pending', 'budget_unconfirmed', 'competitor_pressure', 'missed_commitment', 'gone_quiet')", name=op.f('ck_risks_risk_type')),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('fk_risks_deal_id_deals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risks'))
    )
    op.create_index(op.f('ix_risks_deal_id'), 'risks', ['deal_id'], unique=False)
    op.create_index('uq_risks_deal_id_risk_type_open', 'risks', ['deal_id', 'risk_type'], unique=True, postgresql_where=sa.text("status = 'open'"))
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', 'tool', name='chat_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('streaming', 'complete', 'error', name='message_status'), server_default='complete', nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], name=op.f('fk_chat_messages_session_id_chat_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    op.create_index('ix_chat_messages_session_id_created_at', 'chat_messages', ['session_id', 'created_at'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_chunks_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_chunks')),
    sa.UniqueConstraint('document_id', 'chunk_index', name='document_chunk_index')
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index('ix_document_chunks_embedding', 'document_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': 16, 'ef_construction': 64})
    op.create_table('meetings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('meeting_type', sa.String(length=50), server_default='other', nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'completed', 'cancelled', name='meeting_status'), server_default='scheduled', nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transcript_document_id', sa.UUID(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.Enum('positive', 'neutral', 'negative', 'unknown', name='sentiment'), nullable=True),
    sa.Column('analysis_status', sa.Enum('not_started', 'queued', 'running', 'complete', 'failed', name='analysis_status'), server_default='not_started', nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("meeting_type IN ('discovery', 'demo', 'technical_review', 'security_review', 'negotiation', 'check_in', 'other')", name=op.f('ck_meetings_meeting_type')),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('fk_meetings_deal_id_deals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transcript_document_id'], ['documents.id'], name=op.f('fk_meetings_transcript_document_id_documents'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meetings'))
    )
    op.create_index(op.f('ix_meetings_deal_id'), 'meetings', ['deal_id'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('meeting_id', sa.UUID(), nullable=True),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("activity_type IN ('call', 'email', 'meeting', 'note', 'stage_change', 'document_upload', 'task_completed')", name=op.f('ck_activities_activity_type')),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_activities_contact_id_contacts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('fk_activities_deal_id_deals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_activities_meeting_id_meetings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activities'))
    )
    op.create_index('ix_activities_deal_id_occurred_at', 'activities', ['deal_id', 'occurred_at'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('source_kind', sa.Enum('document', 'record', 'derived', name='source_kind'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('chunk_id', sa.UUID(), nullable=True),
    sa.Column('record_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('speaker', sa.String(length=200), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source_kind <> 'document' OR chunk_id IS NOT NULL", name=op.f('ck_evidence_document_needs_chunk')),
    sa.CheckConstraint("source_kind <> 'record' OR record_ref IS NOT NULL", name=op.f('ck_evidence_record_needs_ref')),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], name=op.f('fk_evidence_chunk_id_document_chunks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('fk_evidence_deal_id_deals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_evidence_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence'))
    )
    op.create_index(op.f('ix_evidence_deal_id'), 'evidence', ['deal_id'], unique=False)
    op.create_table('extracted_facts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('fact_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', 'superseded', name='fact_status'), server_default='pending', nullable=False),
    sa.Column('promoted_to_type', sa.String(length=30), nullable=True),
    sa.Column('promoted_to_id', sa.UUID(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("fact_type IN ('requirement', 'objection', 'stakeholder', 'commitment', 'deadline', 'budget', 'competitor', 'decision_criteria')", name=op.f('ck_extracted_facts_fact_type')),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('fk_extracted_facts_deal_id_deals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_extracted_facts_document_id_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_extracted_facts_meeting_id_meetings'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extracted_facts'))
    )
    op.create_index(op.f('ix_extracted_facts_deal_id'), 'extracted_facts', ['deal_id'], unique=False)
    op.create_table('meeting_attendees',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('raw_name', sa.String(length=200), nullable=True),
    sa.Column('is_internal', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('attended', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('contact_id IS NOT NULL OR raw_name IS NOT NULL', name=op.f('ck_meeting_attendees_identified_somehow')),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_meeting_attendees_contact_id_contacts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_meeting_attendees_meeting_id_meetings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meeting_attendees'))
    )
    op.create_index(op.f('ix_meeting_attendees_meeting_id'), 'meeting_attendees', ['meeting_id'], unique=False)
    op.create_table('meeting_briefs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('objectives', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('context_summary', sa.Text(), nullable=True),
    sa.Column('key_risks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommended_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_meeting_briefs_meeting_id_meetings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meeting_briefs')),
    sa.UniqueConstraint('meeting_id', name='one_per_meeting')
    )
    op.create_table('claim_evidence',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('claim_type', sa.Enum('fact', 'commitment', 'risk', 'recommendation', 'chat_message', name='claim_type'), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('relevance', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('verification_status', sa.Enum('unverified', 'verified', 'span_missing', 'value_drifted', 'stale', name='verification_status'), server_default='unverified', nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], name=op.f('fk_claim_evidence_evidence_id_evidence'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claim_evidence')),
    sa.UniqueConstraint('claim_type', 'claim_id', 'evidence_id', name='claim_evidence_link')
    )
    op.create_index('ix_claim_evidence_claim_type_claim_id', 'claim_evidence', ['claim_type', 'claim_id'], unique=False)
    op.create_index(op.f('ix_claim_evidence_evidence_id'), 'claim_evidence', ['evidence_id'], unique=False)
    op.create_table('commitments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('source_fact_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('owner_side', sa.Enum('us', 'customer', name='owner_side'), nullable=False),
    sa.Column('owner_contact_id', sa.UUID(), nullable=True),
    sa.Column('owner_name', sa.String(length=200), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'met', 'missed', 'waived', name='commitment_status'), server_default='pending', nullable=False),
    sa.Column('origin', sa.Enum('user', 'ai', name='origin'), server_default='ai', nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('fk_commitments_deal_id_deals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_contact_id'], ['contacts.id'], name=op.f('fk_commitments_owner_contact_id_contacts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_fact_id'], ['extracted_facts.id'], name=op.f('fk_commitments_source_fact_id_extracted_facts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_commitments'))
    )
    op.create_index(op.f('ix_commitments_deal_id'), 'commitments', ['deal_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('open', 'done', 'cancelled', name='task_status'), server_default='open', nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', name='priority'), server_default='medium', nullable=False),
    sa.Column('origin', sa.Enum('user', 'ai', name='origin'), server_default='user', nullable=False),
    sa.Column('source_fact_id', sa.UUID(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('fk_tasks_deal_id_deals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_fact_id'], ['extracted_facts.id'], name=op.f('fk_tasks_source_fact_id_extracted_facts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_index(op.f('ix_tasks_deal_id'), 'tasks', ['deal_id'], unique=False)
    op.create_index('ix_tasks_open_due_date', 'tasks', ['due_date'], unique=False, postgresql_where=sa.text("status = 'open'"))
    op.create_table('recommendations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', name='priority'), server_default='medium', nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('status', sa.Enum('suggested', 'accepted', 'dismissed', 'completed', name='recommendation_status'), server_default='suggested', nullable=False),
    sa.Column('origin', sa.Enum('user', 'ai', name='origin'), server_default='ai', nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_task_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action_type IN ('schedule_meeting', 'send_document', 'follow_up_email', 'engage_stakeholder', 'update_close_date', 'address_objection', 'internal_escalation')", name=op.f('ck_recommendations_action_type')),
    sa.ForeignKeyConstraint(['created_task_id'], ['tasks.id'], name=op.f('fk_recommendations_created_task_id_tasks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('fk_recommendations_deal_id_deals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations'))
    )
    op.create_index(op.f('ix_recommendations_deal_id'), 'recommendations', ['deal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendations_deal_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index('ix_tasks_open_due_date', table_name='tasks', postgresql_where=sa.text("status = 'open'"))
    op.drop_index(op.f('ix_tasks_deal_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_commitments_deal_id'), table_name='commitments')
    op.drop_table('commitments')
    op.drop_index(op.f('ix_claim_evidence_evidence_id'), table_name='claim_evidence')
    op.drop_index('ix_claim_evidence_claim_type_claim_id', table_name='claim_evidence')
    op.drop_table('claim_evidence')
    op.drop_table('meeting_briefs')
    op.drop_index(op.f('ix_meeting_attendees_meeting_id'), table_name='meeting_attendees')
    op.drop_table('meeting_attendees')
    op.drop_index(op.f('ix_extracted_facts_deal_id'), table_name='extracted_facts')
    op.drop_table('extracted_facts')
    op.drop_index(op.f('ix_evidence_deal_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index('ix_activities_deal_id_occurred_at', table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_meetings_deal_id'), table_name='meetings')
    op.drop_table('meetings')
    op.drop_index('ix_document_chunks_embedding', table_name='document_chunks', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': 16, 'ef_construction': 64})
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index('ix_chat_messages_session_id_created_at', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('uq_risks_deal_id_risk_type_open', table_name='risks', postgresql_where=sa.text("status = 'open'"))
    op.drop_index(op.f('ix_risks_deal_id'), table_name='risks')
    op.drop_table('risks')
    op.drop_index('ix_documents_deal_id_occurred_at', table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_deal_stage_history_deal_id'), table_name='deal_stage_history')
    op.drop_table('deal_stage_history')
    op.drop_table('deal_contacts')
    op.drop_index(op.f('ix_chat_sessions_deal_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index('ix_deals_stage_expected_close_date', table_name='deals')
    op.drop_index(op.f('ix_deals_account_id'), table_name='deals')
    op.drop_table('deals')
    op.drop_index(op.f('ix_contacts_account_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index('ix_claim_validations_claim_type_claim_id_checked_at', table_name='claim_validations')
    op.drop_table('claim_validations')
    op.drop_table('accounts')
    # ### end Alembic commands ###

    for enum_name in ENUM_TYPES:
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
