"""meeting attendee name always recorded

Deleting a contact fires ON DELETE SET NULL on meeting_attendees.contact_id,
which then violated the `identified_somehow` CHECK for any attendee whose only
identity was that link -- making contacts undeletable once they had attended a
meeting.

Attendance is a historical fact, so the name is now snapshotted on the row and
contact_id is purely the optional resolution to a known person. The CHECK is
redundant once raw_name is NOT NULL.

Revision ID: 0003_attendee_name
Revises: 0002_schema
Create Date: 2026-09-24 17:27:47.635562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003_attendee_name'
down_revision: Union[str, None] = '0002_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Any pre-existing row identified only by contact_id gets a name from the
    # contact it points at, so the NOT NULL below can be satisfied.
    op.execute("""
        UPDATE meeting_attendees ma
           SET raw_name = c.first_name || ' ' || c.last_name
          FROM contacts c
         WHERE ma.contact_id = c.id AND ma.raw_name IS NULL
    """)
    op.execute("UPDATE meeting_attendees SET raw_name = 'Unknown' WHERE raw_name IS NULL")
    op.alter_column('meeting_attendees', 'raw_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # Autogenerate does not detect CHECK constraints -- dropped by hand.
    # Raw SQL rather than op.drop_constraint(): the metadata naming convention
    # would expand the name a second time into
    # ck_meeting_attendees_ck_meeting_attendees_identified_somehow.
    op.execute(
        "ALTER TABLE meeting_attendees "
        "DROP CONSTRAINT ck_meeting_attendees_identified_somehow"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Bare logical name here -- create_check_constraint runs it through the
    # naming convention, which adds the ck_meeting_attendees_ prefix.
    op.create_check_constraint(
        'identified_somehow',
        'meeting_attendees',
        'contact_id IS NOT NULL OR raw_name IS NOT NULL',
    )
    op.alter_column('meeting_attendees', 'raw_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###
